# Generated by Django 4.1.7 on 2023-05-25 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("impact_factor", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Articlemodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PMID", models.IntegerField(null=True)),
                ("Date_publish", models.CharField(max_length=200)),
                ("Title", models.CharField(max_length=200)),
                ("Author", models.CharField(max_length=200, null=True)),
                ("Abstract", models.TextField()),
                ("DOI", models.URLField(null=True)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paper_abstract_app.journal",
                    ),
                ),
            ],
        ),
    ]
